export const config = {
  contractAddress: "0x5c5d6d3d7a948e02c72838f4f4e25fafbfea5559",
  contractAbi: [{
    "constant": true,
    "inputs": [],
    "name": "startDate",
    "outputs": [{"name": "", "type": "uint256"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [{"name": "message", "type": "string"}],
    "name": "doHash",
    "outputs": [{"name": "", "type": "bytes32"}],
    "payable": false,
    "stateMutability": "pure",
    "type": "function",
  }, {
    "constant": false,
    "inputs": [{"name": "hash", "type": "bytes32"}, {"name": "v", "type": "uint8"}, {
      "name": "r",
      "type": "bytes32",
    }, {"name": "s", "type": "bytes32"}, {"name": "value", "type": "uint32"}],
    "name": "Withdraw",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [],
    "name": "customer",
    "outputs": [{"name": "", "type": "address"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [],
    "name": "restaurantOwner",
    "outputs": [{"name": "", "type": "address"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function",
  }, {
    "constant": false,
    "inputs": [{"name": "to", "type": "address"}],
    "name": "Deposit",
    "outputs": [],
    "payable": true,
    "stateMutability": "payable",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [{"name": "message", "type": "string"}, {"name": "v", "type": "uint8"}, {
      "name": "r",
      "type": "bytes32",
    }, {"name": "s", "type": "bytes32"}],
    "name": "checkSignature",
    "outputs": [{"name": "", "type": "address"}],
    "payable": false,
    "stateMutability": "pure",
    "type": "function",
  }],

};
