export const config = {
  contractAddress: "0xBC14b1940732969D8313bEf6BfB2318B4e155dEd",
  contractAbi: [{
    "constant": true,
    "inputs": [],
    "name": "startDate",
    "outputs": [{"name": "", "type": "uint256"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [{"name": "message", "type": "string"}],
    "name": "doHash",
    "outputs": [{"name": "", "type": "bytes32"}],
    "payable": false,
    "stateMutability": "pure",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [],
    "name": "customer",
    "outputs": [{"name": "", "type": "address"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [],
    "name": "restaurantOwner",
    "outputs": [{"name": "", "type": "address"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function",
  }, {
    "constant": false,
    "inputs": [{"name": "to", "type": "address"}],
    "name": "Deposit",
    "outputs": [],
    "payable": true,
    "stateMutability": "payable",
    "type": "function",
  }, {
    "constant": true,
    "inputs": [{"name": "message", "type": "string"}, {"name": "v", "type": "uint8"}, {
      "name": "r",
      "type": "bytes32",
    }, {"name": "s", "type": "bytes32"}],
    "name": "checkSignature",
    "outputs": [{"name": "", "type": "address"}],
    "payable": false,
    "stateMutability": "pure",
    "type": "function",
  }],
};
